package com.society.app.ui.complaints

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import com.society.app.data.model.Complaint
import com.society.app.data.repository.ComplaintRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import java.util.Date
import java.util.UUID
import kotlinx.coroutines.launch
import androidx.lifecycle.viewModelScope
import javax.inject.Inject

@HiltViewModel
class ComplaintViewModel @Inject constructor(
    private val repository: ComplaintRepository
) : ViewModel() {

    private val _complaints = MutableLiveData<List<Complaint>>()
    val complaints: LiveData<List<Complaint>> = _complaints

    init {
        loadComplaints()
    }

    fun loadComplaints() {
        viewModelScope.launch {
            val result = repository.getComplaints()
            result.onSuccess {
                _complaints.value = it
            }
        }
    }

    fun addComplaint(title: String, desc: String, category: String, priority: String) {
        viewModelScope.launch {
            val newComplaint = Complaint(
                id = 0, // ID generated by backend
                title = title,
                description = desc,
                category = category,
                status = "OPEN",
                priority = priority,
                dateCreated = Date().toString(),
                residentName = "Current User",
                apartmentNumber = "101"
            )
            repository.addComplaint(newComplaint)
            loadComplaints() // Refresh list
        }
    }
}
